name: CI

on: [push, pull_request]

env:
  WWWGROUP: 1000
  WWWUSER: 1000
  MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: cp .env.example .env

      - name: Make test certs
        run: ./bin/make-test-certs.sh

      - name: Setup PHP 8.1 to match server
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Build Docker Image
        run: docker compose build

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Check that all services are up
        run: ./bin/check-services.sh

      - name: Install JS dependencies
        run: yarn && yarn prod

      - name: Setup Laravel
        run: docker compose exec -T laravel.test ./bin/ci.sh

      # - name: Lint code
      #   run: npm run lint

      - name: Run unit tests with Jest
        run: npm run jest

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          wait-on: "https://localhost"
          browser: chrome
          config: baseUrl=https://localhost
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      ## Grab any useful artifacts before exiting
      - name: Upload test screenshots if any
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-snapshots
          path: cypress/snapshots

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: "./storage/logs"

      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./storage/logs

      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz
