name: CI

on: [push, pull_request]

env:
  WWWGROUP: 1000
  WWWUSER: 1000
  MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: cp .env.example .env

      - name: Setup PHP 8.1 to match server
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --ignore-platform-reqs

      - name: make test certs
        run: |
          mkdir .cert
          echo "${{ secrets.TEST_CERT_PEM_BASE64 }}" | base64 -d > .cert/cert.pem
          echo "${{ secrets.TEST_KEY_PEM_BASE64 }}" | base64 -d > .cert/key.pem

      - name: Build
        run: docker compose build

      - name: Start
        run: docker compose up -d

      - name: Check service status
        run: docker compose ps --all

      - name: Install JS dependencies
        run: yarn && yarn build

      - name: Laravel Setup
        run: |
          docker compose exec -T laravel.test ./bin/ci.sh
          docker compose exec -T laravel.test php artisan migrate:fresh --seed

      - name: Set ownership
        run: |
          docker compose exec -T laravel.test chown -R $WWWUSER:$WWWGROUP storage

      # - name: Lint code
      #   run: yarn lint

      - name: Run unit tests with Jest
        run: yarn jest

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          wait-on: "https://localhost"
          browser: chrome
          config: baseUrl=https://localhost
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      ## Grab any useful artifacts before exiting
      - name: Upload test screenshots if any
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-snapshots
          path: cypress/snapshots

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: "./storage/logs"

      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./storage/logs

      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz
